Repository k911/swoole-bundle, pull requests merged in 2019-03, with the labels that each got.

#33 Add Swoole-Server Setting for "buffer_output_size"
  src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
  src/Server/HttpServerConfiguration.php
Labels: area/config, area/http-server, kind/feature, priority/important

#36 ci(circle): Set-up commitlint
  .circleci/config.yml
  .editorconfig
  .travis.yml
  commitlint.config.js
Labels: area/ci, kind/feature, priority/backlog, status/wip

#38 ci(travis): Switch distro to ubuntu xenial
  .travis.yml
Labels: area/ci, priority/backlog
