Repository k911/swoole-bundle, pull requests merged in 2020-05, with the labels that each got.

#208 ci(circle): use buildkit for building docker images
  .circleci/Dockerfile
  .circleci/config.yml
  .codecov.yml
  .travis.yml
  CONTRIBUTING.md
  Dockerfile
  composer.json
  docker-bake.hcl
  docker-compose.yml
Labels: area/ci, area/docker, area/tests, kind/other, priority/important

#209 Allow ext-swool 4.5.0
  composer.json
  composer.lock
Labels: area/deps, dependencies, kind/other, priority/important

#220 feat(http_server): add max_request and max_request_grace configuration options
  docs/configuration-reference.md
  src/Bridge/Symfony/Bundle/Command/AbstractServerStartCommand.php
  src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
  src/Server/HttpServerConfiguration.php
Labels: area/config, area/docs, area/symfony-bundle, kind/feature, priority/important, status/waiting-for-contributor

#221 feat(blackfire): Add bridge for upscale/swoole-blackfire
  composer.json
  composer.lock
  docs/configuration-reference.md
  docs/swoole-blackfire.md
  src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
  src/Bridge/Symfony/Bundle/DependencyInjection/SwooleExtension.php
  src/Bridge/Upscale/Blackfire/WithProfiler.php
  tests/Feature/SwooleProfilerRegisteredTest.php
  tests/Unit/Server/Configurator/WithProfilerTest.php
Labels: area/performance, kind/feature, priority/backlog, status/wip

#222 chore(deps): upgrade composer dependencies
  composer.json
  composer.lock
Labels: area/deps, dependencies, kind/other, priority/backlog

#226 MR for #185
  composer.json
  docs/swoole-doctrine.md
Labels: area/deps, kind/other, priority/backlog
