Repository k911/swoole-bundle, pull requests merged in 2021-01, with the labels that each got.

#394 ci(circle): run tests on php 8.0.x
  .circleci/config.yml
  .travis.yml
  composer.json
  composer.lock
Labels: area/ci, area/docker, kind/other, priority/backlog, status/wip

#433 refactor(php): support only PHP 7.4 and up
  .circleci/config.yml
  .php_cs.dist
  .travis.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  composer.json
  composer.lock
  src/Bridge/Symfony/Bundle/Command/AbstractServerStartCommand.php
  src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
  src/Component/ExceptionArrayTransformer.php
  src/Server/Api/ApiServerRequestHandler.php
  src/Server/Runtime/CallableBootManagerFactory.php
  src/functions.php
  tests/Feature/SwooleCommandsRegisteredTest.php
  tests/Feature/SwooleProfilerRegisteredTest.php
  tests/Feature/SwooleServerCustomPidFileTest.php
  tests/Feature/SwooleServerHMRTest.php
  tests/Feature/SwooleServerReloadCommandTest.php
  tests/Feature/SwooleServerReloadViaApiClientTest.php
  tests/Feature/SwooleServerReloadViaHttpApiTest.php
  tests/Feature/SwooleServerRunXdebugRestartedCommandTest.php
  tests/Feature/SwooleServerStatusCommandTest.php
  tests/Feature/SymfonyMessengerSwooleTaskTransportTest.php
  tests/Fixtures/Symfony/TestBundle/Test/ServerTestCase.php
  tests/Unit/Bridge/Symfony/HttpFoundation/CloudFrontRequestFactoryTest.php
  tests/Unit/Bridge/Symfony/HttpFoundation/SetRequestRuntimeConfigurationTest.php
  tests/Unit/Bridge/Symfony/HttpFoundation/TrustAllProxiesRequestHandlerTest.php
  tests/Unit/Client/HttpClientTest.php
  tests/Unit/Component/AtomicCounter/AtomicCounterTest.php
  tests/Unit/Coroutine/CoroutinePoolTest.php
  tests/Unit/Functions/DecodeStringAsSetTest.php
  tests/Unit/Functions/FormatBytesTest.php
  tests/Unit/Functions/GetObjectPropertyTest.php
  tests/Unit/Functions/ReplaceObjectPropertyTest.php
  tests/Unit/Server/Configurator/WithRequestHandlerTest.php
  tests/Unit/Server/Configurator/WithServerManagerStartHandlerTest.php
  tests/Unit/Server/Configurator/WithServerManagerStopHandlerTest.php
  tests/Unit/Server/Configurator/WithServerShutdownHandlerTest.php
  tests/Unit/Server/Configurator/WithServerStartHandlerTest.php
  tests/Unit/Server/Configurator/WithTaskFinishedHandlerTest.php
  tests/Unit/Server/Configurator/WithTaskHandlerTest.php
  tests/Unit/Server/Configurator/WithWorkerStartHandlerTest.php
  tests/Unit/Server/Runtime/HMR/InotifyHMRTest.php
  tests/Unit/Server/WorkerHandler/HMRWorkerStartHandlerTest.php
Labels: area/ci, area/docker, kind/cleanup, priority/backlog, status/wip

#422 Avoid accessing undefined index REQUEST_URI
  src/Bridge/Symfony/HttpFoundation/RequestFactory.php
Labels: area/http-server, kind/bug/fixed, priority/important
